In [1]:
import pandas as pd
import numpy as np
import re
import nltk
import string
import nltk
from nltk.corpus import stopwords
import statistics
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,SimpleRNN,GRU,Bidirectional
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

WARNING:tensorflow:From c:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [6]:
import os
print(os.getcwd())

c:\Users\Dell\Desktop\AML 10 EX

In [10]:
import os

path = r'C:\Users\Dell\Downloads\IMDB Dataset.csv'
print("Exists:", os.path.exists(path))

Exists: False

In [11]:
df = pd.read_csv(r'C:\Users\Dell\Downloads\IMDB Dataset.txt')

In [2]:
df = pd.read_csv(r'C:\Users\Dell\Downloads\IMDB Dataset.csv', 
                 engine='python', 
                 nrows=25000)

NameError: name 'pd' is not defined

In [3]:
import pandas as pd

In [6]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\Dell\Downloads\IMDB Dataset.txt',
    delimiter=',',        # important
    engine='python',
    encoding='latin1',
    on_bad_lines='skip'
)

print(df.head())

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [12]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
import nltk

nltk.download('punkt')
nltk.download('stopwords')

In [16]:
def remove_html_tags(text):
  clean_text = re.sub(r'<.*?>', '', text)
  return clean_text

df['review'] = df['review'].apply(remove_html_tags)
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. The filming tec...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [17]:
import string
punc = string.punctuation
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [18]:
def remove_punc(text):
  clean_text = "".join([char for char in text if char not in punc])
  return clean_text

df['review'] = df['review'].apply(remove_punc)
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production The filming tech...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically theres a family where a little boy J...  negative
4  Petter Matteis Love in the Time of Money is a ...  positive

In [19]:
df['review'] =  df['review'].str.lower()

In [8]:
import pandas as pd
import nltk
from nltk.corpus import stopwords

# 1. Load dataset
df = pd.read_csv(
    r'C:\Users\Dell\Downloads\IMDB Dataset.txt',
    delimiter=',',
    engine='python',
    encoding='latin1',
    on_bad_lines='skip'
)

print("Data Loaded ✅")

# 2. Setup stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# 3. Function
def stp_words(text):
    return " ".join([word for word in text.split() if word not in stop_words])

# 4. Apply
df['review'] = df['review'].apply(stp_words)

print(df.head())

Data Loaded ✅

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                                              review sentiment
0  One reviewers mentioned watching 1 Oz episode ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought wonderful way spend time hot summer ...  positive
3  Basically there's family little boy (Jake) thi...  negative
4  Petter Mattei's "Love Time Money" visually stu...  positive

In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer

WARNING:tensorflow:From c:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [5]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from tensorflow.keras.preprocessing.text import Tokenizer

# 1. Load dataset
df = pd.read_csv(
    r'C:\Users\Dell\Downloads\IMDB Dataset.txt',
    delimiter=',',
    engine='python',
    encoding='latin1',
    on_bad_lines='skip'
)

print("Dataset Loaded ✅")

# 2. Stopwords setup
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# 3. Clean function
def stp_words(text):
    return " ".join([word for word in text.split() if word not in stop_words])

df['review'] = df['review'].apply(stp_words)

# 4. Tokenization
token = Tokenizer()
token.fit_on_texts(df['review'])

print("Tokenization Done ✅")
print(list(token.word_index.items())[:10])

Dataset Loaded ✅

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Tokenization Done ✅
[('br', 1), ('i', 2), ('the', 3), ('movie', 4), ('film', 5), ('one', 6), ('it', 7), ('like', 8), ('this', 9), ('good', 10)]

In [6]:
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer

# example (make sure df already exists!)
token = Tokenizer()

token.fit_on_texts(df['review'])

In [7]:
token = Tokenizer()
token.fit_on_texts(df['review'])

In [8]:
len(token.word_index)

124096

In [9]:
seq = token.texts_to_sequences(df['review'])

In [14]:
average = statistics.mean

In [15]:
average([len(x) for x in seq])

140.06574

In [18]:
padding = pad_sequences(seq,maxlen=220,padding='pre')

NameError: name 'pad_sequences' is not defined